<?php
//$curso1 = "PHP"; $curso2 = "JAVA"; $curso3 = "C++"; $curso4 = "CSS"; $curso5 = "JAVASCRIPT";
//PARA NÃO SER TUDO DIGITADO EM VARIAS VARIAVEIS É CRIADO UM ARRAY DE DADOS.

$cursos = array(
    "PHP",
    "JAVA",
    "C++",
    "CSS",
    "JAVASCRIPT",
    "Python",
    "Ruby",
    "Swift",
    "HTML",
    "SQL",
    "C#",
    "R",
    "Go",
    "TypeScript",
    "Perl",
    "Kotlin",
    "Scala",
    "Lua",
    "Matlab",
    "Rust",
    "Assembly",
    "Bash",
    "Objective-C",
    "Dart",
    "COBOL",
    "Fortran",
    "Haskell",
    "Lisp",
    "Prolog",
    "Ada",
    "Smalltalk",
    "Elixir",
    "F#",
    "Groovy",
    "Julia",
    "Pascal",
    "Scratch",
    "VB.NET",
    "ActionScript",
    "CoffeeScript",
    "D",
    "Erlang",
    "Haxe",
    "Io",
    "Nim",
    "OCaml",
    "Perl",
    "PowerShell",
    "Racket",
    "Xampp" ,
    "Lampp" ,
);
print_r($cursos[46]
);

?>